package com.inventory.backend.model;

import javax.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "sale_items")
public class SaleItem {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "sale_id")
    private Integer saleId;

    @Column(name = "product_id")
    private Integer productId;

    private Integer quantity;

    @Column(name = "unit_price_at_sale")
    private BigDecimal unitPriceAtSale;

    // Remove @Column for subtotal since it's generated by MySQL
    // Do NOT include subtotal in insert/update operations
    @Transient
    private BigDecimal subtotal;

    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    public SaleItem() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    // Getters and Setters (no setter for subtotal)
    public Integer getId() { return id; }
    public void setId(Integer id) { this.id = id; }
    public Integer getSaleId() { return saleId; }
    public void setSaleId(Integer saleId) { this.saleId = saleId; }
    public Integer getProductId() { return productId; }
    public void setProductId(Integer productId) { this.productId = productId; }
    public Integer getQuantity() { return quantity; }
    public void setQuantity(Integer quantity) { this.quantity = quantity; }
    public BigDecimal getUnitPriceAtSale() { return unitPriceAtSale; }
    public void setUnitPriceAtSale(BigDecimal unitPriceAtSale) { this.unitPriceAtSale = unitPriceAtSale; }
    public BigDecimal getSubtotal() {
        // Calculate on the fly instead of storing
        if (quantity != null && unitPriceAtSale != null) {
            return unitPriceAtSale.multiply(BigDecimal.valueOf(quantity));
        }
        return subtotal;
    }
    public void setSubtotal(BigDecimal subtotal) {
        // Do nothing - MySQL generates this
        this.subtotal = subtotal;
    }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
}